"""
This type stub file was generated by pyright.
"""

def open_in_browser(html): # -> str:
    """
    Open the HTML document in a web browser, saving it to a temporary
    file to open it.  Note that this does not delete the file after
    use.  This is mainly meant for debugging.
    """
    ...

